// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWTMiuknbvulqiI8MMYgJxzUDhqeDmfA',
    appId: '1:862031591722:web:b56d7fa2435b1f7d5dc653',
    messagingSenderId: '862031591722',
    projectId: 'casual-networking-b3d23',
    authDomain: 'casual-networking-b3d23.firebaseapp.com',
    storageBucket: 'casual-networking-b3d23.appspot.com',
    measurementId: 'G-NEZ5M3X2JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhWMdYl_8pFiK_NhOq2IN5MxkKdXDMWy8',
    appId: '1:862031591722:android:1a0a35083346e9515dc653',
    messagingSenderId: '862031591722',
    projectId: 'casual-networking-b3d23',
    storageBucket: 'casual-networking-b3d23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHMhb9gPHQW86b3S3u5CSi4j_685fAFmc',
    appId: '1:862031591722:ios:af30b1c1066a87885dc653',
    messagingSenderId: '862031591722',
    projectId: 'casual-networking-b3d23',
    storageBucket: 'casual-networking-b3d23.appspot.com',
    iosClientId: '862031591722-cathl73aqdtfjdgk1suiag43phpqo0pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.casualNetvorking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHMhb9gPHQW86b3S3u5CSi4j_685fAFmc',
    appId: '1:862031591722:ios:f50aa8dd78be1e9f5dc653',
    messagingSenderId: '862031591722',
    projectId: 'casual-networking-b3d23',
    storageBucket: 'casual-networking-b3d23.appspot.com',
    iosClientId: '862031591722-30icmpltqu7ebantfoqkg64kbcqnk5us.apps.googleusercontent.com',
    iosBundleId: 'com.example.casualNetvorking.RunnerTests',
  );
}
